# Generated by Django 2.1 on 2019-01-30 16:12

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('describtion', models.TextField()),
                ('img', models.FileField(blank=True, upload_to=home.models.img_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('files', models.FileField(blank=True, upload_to=home.models.img_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
